.TH "XHYDRA" "1" "02/02/2012"
.SH NAME
xhydra \- Gtk+2 frontend for thc-hydra
.SH SYNOPSIS
Execute xhydra in a terminal to start the application.
.SH DESCRIPTION
Hydra is a parallelized login cracker which supports numerous protocols
to attack. New modules are easy to add, beside that, it is flexible and
very fast.
.LP
.B xhydra
is the graphical fronend for the
.BR hydra (1)
tool.
.SH SEE ALSO
.BR hydra (1),
.BR pw-inspector (1).
.br
.SH AUTHOR
hydra was written by van Hauser <vh@thc.org>

.PP
This manual page was written by Daniel Echeverry <epsilon77@gmail.com>,
for the Debian project (and may be used by others).

